FROM golang:1.4.2

#MAINTAINER dreampuf <soddyque@gmail.com>
#
#RUN mkdir -p /opt/exddd/web/src
#RUN go get github.com/revel/revel
#RUN go get github.com/revel/cmd/revel
#RUN go get github.com/jinzhu/gorm
#
#ENV GOPATH "/opt/exddd/web/"
#
#WORKDIR /opt/exddd/web
#ADD ./src/web /opt/exddd/web/src/
#RUN ./bin/revel package web
